apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-aws
  namespace: aws-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo-aws-service"
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devops
        - name: MONGO_REPLICA_SET
          value: rs0
        command:
        - mongod
        - "--replSet"
        - "rs0"
        - "--bind_ip"
        - "0.0.0.0"
        resources:
          requests:  # Minimum sumber daya yang dijamin
            memory: "512Mi"
            cpu: "500m"
          limits:  # Batas maksimum sumber daya
            memory: "1Gi"
            cpu: "1"
