apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-workers
  namespace: mongodb-cluster
spec:
  replicas: 3  # Dua worker/replica
  serviceName: "mongodb-workers-service"
  selector:
    matchLabels:
      app: mongodb-worker
  template:
    metadata:
      labels:
        app: mongodb-worker
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "devops"
        - name: MONGO_REPLICA_SET
          value: "rs0"  # Tetap dalam replica set "rs0"
        command:
        - mongod
        - "--replSet"
        - "rs0"
        - "--bind_ip"
        - "0.0.0.0"
        - "--wiredTigerCacheSizeGB"
        - "1"  # Batasi cache MongoDB menjadi 1 GB
        resources:  # Batasi penggunaan resource
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-workers-service
  namespace: mongodb-cluster
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: mongodb-worker
