---
- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Copy Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Enable and start Grafana service
  service:
    name: grafana-server
    state: started
    enabled: true
