- name: Remove Grafana GPG key if present
  ansible.builtin.apt_key:
    name: 963FA27710458545
    state: absent
  ignore_errors: yes

- name: Install Required Dependencies for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Start Docker Service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Pull MongoDB Docker Image
  ansible.builtin.docker_image:
    name: "{{ docker_image }}"
    source: pull

- name: Stop Existing MongoDB Container (if any)
  ansible.builtin.shell: |
    docker stop mongodb || true
    docker rm mongodb || true

- name: Run MongoDB Docker Container
  ansible.builtin.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ docker_port }}:27017"
    volumes:
      - "mongodb_data:/data/db"
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devops
  when: ansible_distribution == "Ubuntu"
