- name: Add MongoDB repository for Amazon Linux
  ansible.builtin.yum_repository:
    name: mongodb-org-6.0
    description: MongoDB Repository
    baseurl: "{{ mongodb_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ mongodb_repo_gpgkey }}"
    enabled: yes
  when: ansible_facts['distribution'] == "Amazon"

- name: Remove conflicting curl-minimal package (Amazon Linux)
  ansible.builtin.yum:
    name: curl-minimal
    state: absent
  when: ansible_facts['distribution'] == "Amazon"

- name: Install curl (Amazon Linux)
  ansible.builtin.yum:
    name: curl
    state: present
  when: ansible_facts['distribution'] == "Amazon"
