- name: Install Required Packages for Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  when: inventory_hostname in groups['mongodb']

- name: Add Docker GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: inventory_hostname in groups['mongodb']

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: inventory_hostname in groups['mongodb']

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  when: inventory_hostname in groups['mongodb']

- name: Start Docker Service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  when: inventory_hostname in groups['mongodb']

- name: Pull MongoDB Docker Image
  ansible.builtin.docker_image:
    name: "{{ docker_image }}"
    source: pull
  when: inventory_hostname in groups['mongodb']

- name: Stop Existing MongoDB Container (if any)
  ansible.builtin.shell: |
    docker stop mongodb || true
    docker rm mongodb || true
  when: inventory_hostname in groups['mongodb']

- name: Run MongoDB Docker Container
  ansible.builtin.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ docker_port }}:27017"
    volumes:
      - "mongodb_data:/data/db"
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devops
  when: inventory_hostname in groups['mongodb']
