roles:
  - name: mongodb
    src: https://github.com/matahariku/cafe-nangka.git
    scm: git
    version: main
    path: ansible/roles/mongodb

roles:
  - name: grafana
    src: https://github.com/matahariku/cafe-nangka.git
    scm: git
    version: main
    path: ansible/roles/grafana
