roles:
  - name: mongodb
    src: https://github.com/matahariku/mongodb-role.git
    scm: git
    version: main
  - name: grafana
    src: https://github.com/matahariku/grafana-role.git
    scm: git
    version: main
