name: Déployer la configuration Kubernetes avec Ansible

on:
  push:
    branches:
      - main  # Ce workflow s'exécute lors d'un push sur la branche principale
  workflow_dispatch:  # Ce workflow peut aussi être exécuté manuellement via l'interface GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest  # Exécution du workflow sur un runner Ubuntu

    steps:
    - name: Vérification du code
      uses: actions/checkout@v2  # Récupère la dernière version du code depuis le repository

    - name: Configuration d'Ansible
      uses: gaurdian/ansible@v2  # Installe Ansible sur le runner GitHub Actions

    - name: Copier le kubeconfig sur les nœuds cibles
      run: |
        # Exécute le playbook Ansible situé dans le répertoire root
        ansible-playbook ansible/copy_kubeconfig.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"  # Désactive la vérification des clés SSH lors de la première connexion
        ANSIBLE_SSH_PRIVATE_KEY_FILE: ${{ secrets.ANSIBLE_PRIVATE_KEY }}  # Clé privée SSH stockée dans les secrets GitHub
        ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}  # Utilisateur SSH pour la connexion (par exemple, ubuntu ou ec2-user)
