name: Deploy AWS Instances mongodb & grafana

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set Up Key Pair
    - name: Set Up Key Pair
      run: |
        echo "${{ secrets.AWS_KEY_PAIR }}" > key_cafe.pem
        chmod 400 key_cafe.pem

    # 3. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 4. Set Environment Variables
    - name: Set Environment Variables
      run: |
        echo "TF_VAR_key_name=key_cafe" >> $GITHUB_ENV
        echo "TF_VAR_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
        echo "TF_VAR_grafana_ami=${{ secrets.GRAFANA_AMI }}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_ami=${{ secrets.MONGODB_AMI }}" >> $GITHUB_ENV
        echo "TF_VAR_instance_type=t2.micro" >> $GITHUB_ENV
        echo "TF_VAR_vpc_cidr=10.0.0.0/16" >> $GITHUB_ENV
        echo "TF_VAR_public_subnet_cidr=10.0.1.0/24" >> $GITHUB_ENV
        echo "TF_VAR_private_subnet_cidr=10.0.2.0/24" >> $GITHUB_ENV

    # 5. Debug Variables (Opsional)
    - name: Debug Environment Variables
      run: |
        echo "TF_VAR_key_name=$TF_VAR_key_name"
        echo "TF_VAR_region=$TF_VAR_region"
        echo "TF_VAR_grafana_ami=$TF_VAR_grafana_ami"
        echo "TF_VAR_mongodb_ami=$TF_VAR_mongodb_ami"

    # 6. Terraform Init
    - name: Terraform Init
      run: terraform init -input=false
      working-directory: terraform/

    # 7. Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: terraform/

    # 8. Terraform Apply
    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
      working-directory: terraform/
