name: Deploy AWS Instances MongoDB & Grafana

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

  #2. Configure AWS é Debug AWS
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v3
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      aws-region: ${{ secrets.AWS_REGION }}

  - name: Debug AWS Credentials
    run: |
      echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
      echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}"
      aws sts get-caller-identity
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}


    # 3. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 4. Set Environment Variables
    - name: Set Environment Variables
      run: |
        echo "TF_VAR_key_name=${{ secrets.KEY_CAFE }}" >> $GITHUB_ENV
        echo "TF_VAR_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
        echo "TF_VAR_grafana_ami=${{ secrets.GRAFANA_AMI }}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_ami=${{ secrets.MONGODB_AMI }}" >> $GITHUB_ENV
        echo "TF_VAR_instance_type=t2.micro" >> $GITHUB_ENV
        echo "TF_VAR_vpc_cidr=10.0.0.0/16" >> $GITHUB_ENV
        echo "TF_VAR_public_subnet_cidr=10.0.1.0/24" >> $GITHUB_ENV
        echo "TF_VAR_private_subnet_cidr=10.0.2.0/24" >> $GITHUB_ENV

    # 5. Debug Environment Variables
    - name: Debug Environment Variables
      run: |
        echo "TF_VAR_key_name=$TF_VAR_key_name"
        echo "TF_VAR_region=$TF_VAR_region"
        echo "TF_VAR_grafana_ami=$TF_VAR_grafana_ami"
        echo "TF_VAR_mongodb_ami=$TF_VAR_mongodb_ami"

    # 6. Terraform Init
    - name: Terraform Init
      run: terraform init -input=false
      working-directory: terraform/

    # 7. Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: terraform/

    # 8. Terraform Apply
    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
      working-directory: terraform/
