name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init -reconfigure -chdir=terraform/aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # Validate Terraform
      - name: Validate Terraform Configuration
        run: terraform validate -chdir=terraform/aws

      # Plan Terraform Changes
      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan -chdir=terraform/aws

      # Apply Terraform Plan
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan -chdir=terraform/aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
