name: Installer K3s et kubectl

on:
  workflow_dispatch: # Permet de lancer manuellement le workflow

jobs:
  setup-k3s:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le dépôt
      - name: Vérifier le dépôt
        uses: actions/checkout@v3

      # 2. Installer les dépendances nécessaires
      - name: Installer les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget

      # 3. Installer K3s
      - name: Installer K3s
        run: |
          curl -sfL https://get.k3s.io | sh -
          sudo ln -s /usr/local/bin/k3s /usr/bin/k3s
          sudo k3s kubectl get nodes

      # 4. Modifier les permissions et configurer kubectl
      - name: Configurer kubectl et définir les permissions
        run: |
          # Créer le répertoire .kube s'il n'existe pas déjà
          mkdir -p $HOME/.kube
          
          # Changer la propriété du fichier k3s.yaml pour qu'il soit accessible par l'utilisateur runner
          sudo chown runner:runner /etc/rancher/k3s/k3s.yaml
          
          # Copier le fichier k3s.yaml dans .kube/config
          cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
          
          # Changer les permissions du fichier pour s'assurer que seul l'utilisateur runner peut y accéder
          chmod 600 $HOME/.kube/config

          # Vérifier la version de kubectl
          export KUBEVERSION=$(kubectl version --short | awk -Fv '/Client Version/ {print $3}')
          echo "La version de Kubernetes est $KUBEVERSION"

      # 5. Tester kubectl
      - name: Tester kubectl
        run: |
          echo "Tester kubectl"
          kubectl get nodes
