name: Deploy MongoDB Cluster (AWS)

on:
  workflow_dispatch: # Pemicu manual

jobs:
  deploy-mongodb-aws:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY_BLOC4 }}" > ~/.ssh/KEY_BLOC4.pem
          chmod 600 ~/.ssh/KEY_BLOC4.pem

      # 3. Copy MongoDB YAML file to AWS
      - name: Copy MongoDB YAML file
        run: |
          scp -o StrictHostKeyChecking=no k3s/mongo-statefulset-aws.yaml ${{ secrets.EC2_USER_MONGODB }}@${{ secrets.EC2_PUBLIC_IP_MONGODB }}:~/k3s/mongo-statefulset-aws.yaml

      # 4. Deploy MongoDB StatefulSet
      - name: Deploy MongoDB StatefulSet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER_MONGODB }}@${{ secrets.EC2_PUBLIC_IP_MONGODB }} << EOF
          echo "Deploying MongoDB StatefulSet to K3s..."
          kubectl apply -f ~/k3s/mongo-statefulset-aws.yaml
          echo "Verifying MongoDB Deployment..."
          kubectl get pods -n mongodb-cluster
          kubectl get svc mongodb-aws-service -n mongodb-cluster
          EOF
