name: MongoDB HA Deployment

on:
  workflow_dispatch:

jobs:
  deploy-aws-cluster:
    name: Deploy MongoDB on AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup K3s on AWS
        run: |
          curl -sfL https://get.k3s.io | sh -
          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl config set-cluster default --server=https://$EC2_IP_PUBLIC_MONGODB:6443
          kubectl get nodes
        env:
          EC2_IP_PUBLIC_MONGODB: ${{ secrets.EC2_IP_PUBLIC_MONGODB }}

      - name: Create namespace and deploy MongoDB
        run: |
          kubectl create namespace aws-namespace || true
          kubectl apply -f ./k3s/mongo-statefulset-aws.yaml -n aws-namespace

  deploy-ovh-cluster:
    name: Deploy MongoDB on OVH
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup K3s on OVH
        run: |
          curl -sfL https://get.k3s.io | sh -
          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl get nodes

      - name: Create namespace and deploy MongoDB
        run: |
          kubectl create namespace ovh-namespace || true
          kubectl apply -f ./k3s/mongo-statefulset-ovh.yaml -n ovh-namespace
