name: Déploiement HA MongoDB avec Minikube

on:
  workflow_dispatch:

jobs:
  deploy-clusters:
    name: Déployer MongoDB sur AWS et OVH avec Minikube
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le dépôt
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      # 2. Afficher la hiérarchie des fichiers
      - name: Afficher la hiérarchie des fichiers
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tree
          tree -L 2 # Affiche jusqu'à deux niveaux de répertoires

      # 3. Installer Minikube sur AWS
      - name: Installer Minikube sur AWS
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --profile aws-cluster --kubernetes-version=v1.26.0 --cpus=2 --memory=4g --driver=docker
          minikube kubectl -- --context=aws-cluster get nodes
        env:
          EC2_PUBLIC_IP_MONGODB: ${{ secrets.EC2_PUBLIC_IP_MONGODB }}

      # 4. Déployer MongoDB sur AWS
      - name: Déployer MongoDB sur AWS
        run: |
          minikube kubectl -- --context=aws-cluster create namespace aws-namespace || true
          minikube kubectl -- --context=aws-cluster apply -f ./minikube/mongo-statefulset-aws.yaml -n aws-namespace

      # 5. Installer Minikube sur OVH
      - name: Installer Minikube sur OVH
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --profile ovh-cluster --kubernetes-version=v1.26.0 --cpus=2 --memory=4g --driver=docker
          minikube kubectl -- --context=ovh-cluster get nodes

      # 6. Déployer MongoDB sur OVH
      - name: Déployer MongoDB sur OVH
        run: |
          minikube kubectl -- --context=ovh-cluster create namespace ovh-namespace || true
          minikube kubectl -- --context=ovh-cluster apply -f ./minikube/mongo-statefulset-ovh.yaml -n ovh-namespace
