name: Deploy MongoDB Cluster

on:
  workflow_dispatch: # Untuk trigger manual

jobs:
  deploy-mongodb:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configure K3s Access
      - name: Configure K3s Access
        run: |
          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          sudo chmod 600 ~/.kube/config

      # 3. Deploy MongoDB StatefulSet
      - name: Deploy MongoDB StatefulSet
        run: |
          echo "Deploying MongoDB StatefulSet"
          kubectl apply -f ./k3s/mongo-statefulset-aws.yaml
          echo "Verifying MongoDB Pods"
          kubectl get pods -n mongodb-cluster
          echo "Verifying MongoDB Service"
          kubectl get svc -n mongodb-cluster

      # 4. Initialize Replica Set
      - name: Initialize MongoDB Replica Set
        run: |
          echo "Initializing MongoDB Replica Set"
          kubectl exec -it mongodb-aws-0 -n mongodb-cluster -- mongo --eval '
          rs.initiate({
            _id: "rs0",
            members: [
              { _id: 0, host: "mongodb-aws-0.mongodb-aws-service:27017" },
              { _id: 1, host: "mongodb-aws-1.mongodb-aws-service:27017" },
              { _id: 2, host: "mongodb-aws-2.mongodb-aws-service:27017" }
            ]
          });'
          echo "Verifying Replica Set Status"
          kubectl exec -it mongodb-aws-0 -n mongodb-cluster -- mongo --eval 'rs.status();'
