name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up K3s
      run: |
        curl -sfL https://get.k3s.io | sh -

    - name: Verify K3s Installation
      run: |
        k3s --version

    - name: Set up K3S kubeconfig
      run: |
        mkdir -p $HOME/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
        sudo chown $USER:$USER $HOME/.kube/config
        sudo chmod 600 $HOME/.kube/config
        kubectl get nodes

    - name: Check files in terraform/cluster/
      run: |
        ls -la terraform/cluster/

    - name: Deploy MongoDB
      run: |
        kubectl apply -f terraform/cluster/mongo-deployment.yaml

    - name: Deploy Grafana
      run: |
        kubectl apply -f terraform/cluster/grafana-deployment.yaml

    - name: Verify MongoDB Deployment
      run: |
        kubectl get pods -l app=mongodb

    - name: Verify Grafana Deployment
      run: |
        kubectl get pods -l app=grafana

    - name: Verify Deployment
      run: |
        kubectl get pods
