name: Destroy AWS Resources

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init -input=false
      working-directory: terraform/

    - name: Terraform Destroy
      run: |
        terraform destroy -input=false -auto-approve \
          -var "key_name=${{ secrets.KEY_CAFE }}" \
          -var "region=${{ secrets.AWS_REGION }}" \
          -var "grafana_ami=${{ secrets.GRAFANA_AMI }}" \
          -var "mongodb_ami=${{ secrets.MONGODB_AMI }}" \
          -var "instance_type=t2.micro" \
          -var "vpc_cidr=10.0.0.0/16" \
          -var "public_subnet_cidr=10.0.1.0/24" \
          -var "private_subnet_cidr=10.0.2.0/24"
      working-directory: terraform/
