name: Destroy AWS Resources

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init -input=false -chdir=terraform/aws

      - name: Terraform Destroy
        run: |
          terraform destroy -input=false -auto-approve \
            -var "key_name=${{ secrets.KEY_CAFE }}" \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "grafana_ami=${{ secrets.GRAFANA_AMI }}" \
            -var "mongodb_ami=${{ secrets.MONGODB_AMI }}" \
            -var "instance_type=t2.micro" \
            -var "vpc_cidr=10.0.0.0/16" \
            -var "public_subnet_cidr=10.0.1.0/24" \
            -var "private_subnet_cidr=10.0.2.0/24"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
