name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: mongo

    steps:
      - name: Test Runner Connection
        run: |
          echo "Runner aktif dan berjalan!"
          uname -a
