name: Display Tree of Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  display-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Tree Command
        run: sudo apt-get install tree

      - name: Display File Tree
        run: |
          # Affichage de la structure des fichiers à la racine
          tree -L 2 
          
          # Affichage de la structure dans le répertoire .github/workflows
          cd .github/workflows
          tree -L 2
          cd ../..

          cd terraform/aws
          tree -L 2
          cd ../..

          # Affichage de la structure dans le répertoire ansible/roles
          cd ansible/roles
          tree -L 2
          cd ../..

          # Affichage de la structure dans le répertoire mongodb
          cd ansible/roles/mongodb 
          tree -L 2
          cd ../../..

          # Affichage de la structure dans le répertoire grafana
          cd ansible/roles/grafana
          tree -L 2
          cd ..
