name: Display Tree of Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  display-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Tree Command
        run: sudo apt-get install tree

      - name: Display File Tree
        run: |
          # Menampilkan struktur file di root
          tree -L 2 
          
          # Menampilkan struktur di direktori .github/workflows
          cd .github/workflows
          tree -L 2
          cd ../..

          # Menampilkan struktur di direktori ansible/roles
          cd ansible/roles
          tree -L 2
          cd ../..

          # Menampilkan struktur di direktori mongodb
          cd mongodb
          tree -L 2
          cd ..

          # Menampilkan struktur di direktori grafana
          cd grafana
          tree -L 2
          cd ..
